version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    #grafana new release changed default user to non-root
    #issue "id -u" command, then replace below user id
    user: "1000"
    links:
      - influxdb
    env_file:
      - 'env.grafana'
    #make sure that the volum binding ownership is set to current user
    #again, grafana new release changed default user to non-root
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf:latest
#    network_mode: "host"
    links:
      - influxdb
    volumes:
      - ./volumes/telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
